### PR TITLE
Re-bind HCL program before passing it to each language rendering

### LINKED ISSUE #1479: network.SubnetTypeArgs does not implement network.SubnetTypeArrayInput (missing ToSubnetTypeArrayOutput method)
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm trying out this piece of code from [here](https://www.pulumi.com/registry/packages/azure-native/api-docs/network/virtualnetwork/#create-virtual-network-with-subnet) to create an Azure VNET with subnets:

I get the following error:
```
network.SubnetTypeArgs does not implement network.SubnetTypeArrayInput (missing ToSubnetTypeArrayOutput method)
```

### Steps to reproduce

I'm using the code from [here](https://www.pulumi.com/registry/packages/azure-native/api-docs/network/virtualnetwork/#create-virtual-network-with-subnet) to create an Azure VNET with subnets as follows:

```go
	_, err = network.NewVirtualNetwork(ctx, "virtualNetwork", &network.VirtualNetworkArgs{
		AddressSpace: &network.AddressSpaceArgs{
			AddressPrefixes: pulumi.StringArray{
				pulumi.String(addressPrefix[0]),
			},
		},
		Subnets: network.SubnetTypeArgs{
			AddressPrefix: pulumi.String("10.0.1.0/24"),
			Name:          pulumi.String("subnet1"),
			ServiceEndpoints: network.ServiceEndpointPropertiesFormatArray{
				&network.ServiceEndpointPropertiesFormatArgs{
					Service: pulumi.String("Microsoft.Storage"),
				},
				&network.ServiceEndpointPropertiesFormatArgs{
					Service: pulumi.String("Microsoft.ContainerRegistry"),
				},
			},
		},
		Location:           pulumi.String(location),
		ResourceGroupName:  pulumi.String(resourceGroup),
		VirtualNetworkName: pulumi.String(vnetName),
		Tags:               pulumi.ToStringMap(tags),
	})
```
1.  Create a GO Pulumi program using the example [here](https://www.pulumi.com/registry/packages/azure-native/api-docs/network/virtualnetwork/#create-virtual-network-with-subnet) to create an Azure VNET with subnets:
2.  Run the Pulumi program 

Expected: 
- Create a VNET with the specified subnet

Actual: 

```
    # azure-hub
    ./hub.go:86:3: cannot use network.SubnetTypeArgs{...} (type network.SubnetTypeArgs) as type network.SubnetTypeArrayInput in field value:
        network.SubnetTypeArgs does not implement network.SubnetTypeArrayInput (missing ToSubnetTypeArrayOutput method)
```

Program doesn't compile because the passed in struct type  `network.SubnetArgs` doesn't seem to qualify as an implementation of the interface `network.SubnetTypeArrayInput`  because it doesn't implement the method `ToSubnetTypeArrayOutput`. The error appears to be correct whilst skimming through the code for [subnet.go](https://github.com/pulumi/pulumi-azure-native/blob/master/sdk/go/azure/network/v20210501/subnet.go).

I'm using:
```
$ go version
go version go1.17.6 linux/am
```
I'm I'm using the following version of go modules:
```
	github.com/pulumi/pulumi-azure-native/sdk v1.55.0
	github.com/pulumi/pulumi/sdk/v3 v3.23.2
```

### LINKED ISSUE #2047: Error in Go docs for Azure Native Network Security Group resource
### What happened?

I was reviewing the API docs for the Network Security Group (NSG) resource of the Azure Native provider (https://www.pulumi.com/registry/packages/azure-native/api-docs/network/networksecuritygroup/) while writing some Go code to create an NSG. I noted that the "Create network security group with rule" example for Go is incorrect.

The example has:
```
			SecurityRules: []network.SecurityRuleTypeArgs{
				&network.SecurityRuleTypeArgs{
					Access:                   pulumi.String("Allow"),
```
But it _should_ be:
```
			SecurityRules: []network.SecurityRuleTypeArray{
				&network.SecurityRuleTypeArgs{
					Access:                   pulumi.String("Allow"),
```

### Steps to reproduce

1. Create a new Pulumi project using Go and the Azure Native provider.
2. Write code that creates an NSG using the example code found here: https://www.pulumi.com/registry/packages/azure-native/api-docs/network/networksecuritygroup/
3. Run `pulumi up`. It will error.

### Expected Behavior

I expected the documentation to correctly reflect how to use Go with the Azure Native provider to create an NSG.

### Actual Behavior

The documentation was incorrect.

### Output of `pulumi about`

```
CLI
Version      3.43.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.80.0
go            unknown

Host
OS       darwin
Version  12.6
Arch     arm64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.18.5 darwin/arm64'

Current Stack: westus2

Found no resources associated with westus2

Found no pending operations associated with westus2

Backend
Name           pulumi.com
URL            https://app.pulumi.com/scottslowe
User           scottslowe
Organizations  scottslowe

Dependencies:
NAME                                       VERSION
github.com/pulumi/pulumi-azure-native/sdk  1.80.0
github.com/pulumi/pulumi/sdk/v3            3.40.1

Pulumi locates its logs in /var/folders/c_/1pdwtg4j5zx4dvx5t6qp9v180000gn/T/ by default
```

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #2083: Python docs ContainerGroupNetworkProfileResponseArgs should be ContainerGroupNetworkProfileArgs
Per example from docs: File: [themes/default/content/registry/packages/azure-native/api-docs/containerinstance/containergroup/_index.md](https://www.pulumi.com/registry/packages/azure-native/api-docs/containerinstance/containergroup/)

Python docs ContainerGroupNetworkProfileResponseArgs should be ContainerGroupNetworkProfileArgs

### LINKED ISSUE #2084: `SBSkuArgs` instead of `SBSkuResponseArgs` in docs
File: [themes/default/content/registry/packages/azure-native/api-docs/servicebus/namespace/_index.md](https://www.pulumi.com/registry/packages/azure-native/api-docs/servicebus/namespace/)

Here https://www.pulumi.com/registry/packages/azure-native/api-docs/servicebus/namespace/#namespacecreate should be `SBSkuArgs` instead of `SBSkuResponseArgs` in docs.

```
import pulumi
import pulumi_azure_native as azure_native

namespace = azure_native.servicebus.Namespace("namespace",
    location="South Central US",
    namespace_name="sdk-Namespace2924",
    resource_group_name="ArunMonocle",
    sku=azure_native.servicebus.SBSkuResponseArgs(
        name=azure_native.servicebus.SkuName.STANDARD,
        tier=azure_native.servicebus.SkuTier.STANDARD,
    ),
    tags={
        "tag1": "value1",
        "tag2": "value2",
    })
```
Should be
```
import pulumi
import pulumi_azure_native as azure_native

namespace = azure_native.servicebus.Namespace("namespace",
    location="South Central US",
    namespace_name="sdk-Namespace2924",
    resource_group_name="ArunMonocle",
    sku=azure_native.servicebus.SBSkuArgs(
        name=azure_native.servicebus.SkuName.STANDARD,
        tier=azure_native.servicebus.SkuTier.STANDARD,
    ),
    tags={
        "tag1": "value1",
        "tag2": "value2",
    })
```

### LINKED ISSUE #2275: PrivateEndpoint docs go example throws syntax error
### What happened?

The GO example for PrivateEndpoint:
https://www.pulumi.com/registry/packages/azure-native/api-docs/network/privateendpoint/#create-private-endpoint
Does not pass syntax checks with this error related to the `PrivateLinkServiceConnections` property:
```
cannot use ([]network.PrivateLinkServiceConnectionArgs literal) (value of type []network.PrivateLinkServiceConnectionArgs) as network.PrivateLinkServiceConnectionArrayInput value in struct literal: []network.PrivateLinkServiceConnectionArgs does not implement network.PrivateLinkServiceConnectionArrayInput (missing method ElementType)
```

The correct setting for that property appears to be
```
			PrivateLinkServiceConnections: network.PrivateLinkServiceConnectionArray{
				&network.PrivateLinkServiceConnectionArgs{
					GroupIds: pulumi.StringArray{
						pulumi.String("groupIdFromResource"),
					},
					Name:                 pulumi.String("testPlc"),
					PrivateLinkServiceId: pulumi.String("/subscriptions/subId/resourceGroups/rg1/providers/Microsoft.Network/privateLinkServices/testPls"),
					RequestMessage:       pulumi.String("Please approve my connection."),
				},
                       }
```

NOTE: This is what `pulumi convert --language go` using the YAML example produced and it is untested other than it not throwing syntax errors.

### Expected Behavior

The Go example should pass syntax checking.

### Steps to reproduce

1. `pulumi new azure-go`
2. copy/paste the Go example from https://www.pulumi.com/registry/packages/azure-native/api-docs/network/privateendpoint/#create-private-endpoint into the `main.go`
3. Note the error.

### Output of `pulumi about`

CLI          
Version      3.55.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.93.0
go            unknown

Host     
OS       darwin
Version  12.5.1
Arch     x86_64

This project is written in go: executable='/usr/local/bin/go' version='go version go1.18.4 darwin/amd64'

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/xxxxx

Dependencies:
NAME                                       VERSION
github.com/pulumi/pulumi-azure-native/sdk  1.93.0
github.com/pulumi/pulumi/sdk/v3            3.55.0

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #2575: Incorrect types shown in autogenerated documentation
### What happened?

I was attempting to use the Python code provided as an example [here](https://www.pulumi.com/registry/packages/azure-native/api-docs/compute/virtualmachine/) and was getting an error. The example code uses types like `NetworkProfileResponseArgs`, `OSProfileResponseArgs`, and `StorageProfileResponseArgs` when the correct types are supposed to be `NetworkProfileArgs`, `OSProfileArgs`, and `StorageProfileArgs`. This appears to only affect the Python code; the C# code looks like it's using the correct type names. (There are no examples for Go yet.)

### Expected Behavior

I expected the documentation to show the correct types and arguments to use.

### Steps to reproduce

1. Copy the Python code from https://www.pulumi.com/registry/packages/azure-native/api-docs/compute/virtualmachine/ into a Pulumi program
2. Run `pulumi up`. Pulumi will report an error related to an incorrect or missing type.

### Output of `pulumi about`

N/A

### Additional context

This issue was reported by a user in the Pulumi Community Slack.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #2608: Databricks example shows wrong type
### What happened?

In [this example](https://www.pulumi.com/registry/packages/azure-native/api-docs/databricks/workspace/#create-a-workspace-which-is-ready-for-customer-managed-key-cmk-encryption):

```python
import pulumi
import pulumi_azure_native as azure_native

workspace = azure_native.databricks.Workspace("workspace",
    location="westus",
    managed_resource_group_id="/subscriptions/subid/resourceGroups/myManagedRG",
    parameters=azure_native.databricks.WorkspaceCustomParametersResponseArgs(
        prepare_encryption=azure_native.databricks.WorkspaceCustomBooleanParameterArgs(
            value=True,
        ),
    ),
    resource_group_name="rg",
    workspace_name="myWorkspace")
```

The parameters type is wrong: `azure_native.databricks.WorkspaceCustomParametersResponseArgs`

### Expected Behavior

It should be: `azure_native.databricks.databricks.WorkspaceCustomParametersArgs`:

```python
workspace = databricks.Workspace("workspace",
                                 managed_resource_group_id=managed_resource_group.id,
                                 resource_group_name=resource_group.name,
                                 parameters=databricks.WorkspaceCustomParametersArgs(
                                     prepare_encryption=databricks.WorkspaceCustomBooleanParameterArgs(
                                         value=True
                                     )
                                 )
                                 )
```

### Steps to reproduce

n/a

### Output of `pulumi about`

This is the same in v1 and v2 of the provider

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #2827: Many Go samples in schema and registry are not formatted
For instance, [FleetUpdateStrategy](https://www.pulumi.com/registry/packages/azure-native/api-docs/containerservice/fleetupdatestrategy/) looks like this.
Screenshot 2023-10-13 at 11 41 39

This affects _only the Go samples_.

The unindented source is present in the emitted schema, so it's not a registry problem.

Stepping through in the debugger shows that these samples cannot be formatted by go/format because they are not syntactically valid. Pulumi/pulumi codegen then [uses the unformatted code and emits a diagnostic warning](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/go/gen_program.go#L443) that we didn't notice.

As an example, the FleetUpdateStrategy code shown in the screenshot shows these gofmt errors that I can repro locally:
```
gofmt ~/main.go
/Users/tkappler/main.go:14:12: missing ',' in composite literal
/Users/tkappler/main.go:25:19: missing ',' in argument list
/Users/tkappler/main.go:26:1: expected operand, found '}'
/Users/tkappler/main.go:27:1: missing ',' in argument list
/Users/tkappler/main.go:28:1: expected operand, found 'return'
/Users/tkappler/main.go:29:2: missing ',' before newline in argument list
/Users/tkappler/main.go:30:1: expected operand, found 'return'
/Users/tkappler/main.go:31:1: expected operand, found '}'
/Users/tkappler/main.go:32:2: missing ',' in argument list
```

We don't know when this issue started appearing. The change in codegen to use unformatted code in case of formatting errors is pulumi/pulumi#13053 from May 30, which seems a bit old for us not to notice until now.

### PR DESCRIPTION
**Pull request by mikhailshilkov**
### Problem

Program generation (`x.GenerateProgram` functions for each language) have side effects since they change the `program` object passed to them in-place. Currently, we pass the same `program` object through the entire pipleline of example generation for all languages. This means, that all languages except nodejs (which is the first in the list) is affected by previous languages in subtle ways.

Mostly, this seems to break schema type information in hard-to-understand ways. See the list of issues and a diff link below for examples.

### Change

This PR moves the invocation of `hcl2.BindProgram` inside the language loop, which prevents us from sharing the `program`. This should eliminate the cross-language effects.

Entirely unexpectedly to me, this leads to a substantial performance _gain_ not penalty: the schema generation time reduced from 110s to 13s on my laptop!

The second code change you see here is extending the ability to write examples to disk from HCL-only to any language. (see below)

### Validation

I logged all examples in all languages before and after the change, and pushed them to [this PR](https://github.com/pulumi/pulumi-azure-native/pull/3134). This way it's easier to validate the results.

700+ python, 200+ go, and a number of csharp examples are pure improvements with better type instantiations. The only seeming regression are C# changes from `new[] {}` to `new() {}` where the old option looks correct. I guess that's something that worked by luck then?

### Issues Fixed

Fix #2608
Fix #2575
Fix #2084
Fix #2083
Fix #2275
Fix #2047
Fix #1479
Fix #2827 (the example it shows is fixed)

### CODE REVIEW

**Review by thomas11 — APPROVED** [review]
Wow, this is great! How widespread is the new C# issue?

**Comment by mikhailshilkov** [comment]
> How widespread is the new C# issue?

22 examples...

**Comment by mikhailshilkov** [comment]
I manually confirmed that the C# issue isn't new, it's just this PR adds a few new instances of it. This is pre-change:
image

**Review by danielrbradley — APPROVED** [review]
Looks great! I wonder if the speedup is actually due to less examples failing where failure actually takes longer that success.

Does this also make the example generation stable so it doesn't get a different output each time it runs?

**Comment by thomas11** [comment]
> > Does this also make the example generation stable so it doesn't get a different output each time it runs?
> 
> This is a bit tricky to prove. If I just run `make generate_docs` multiple times, I don't get flaky changes. However, that may have been the case in the past too? I have a sense that flakiness always depended on something else, like re-compiling codegen, potentially on a different machine?

Yeah, I wrote a script a few months ago that ran `make generate_docs` many times but it never flaked. It's some global state, I believe.

**Pull request merged**
