### PR TITLE
Custom diff handling for Manager Cluster SKU

### PR DESCRIPTION
**Pull request by mikhailshilkov**
Provides a workaround for diffing of AKS manager cluster SKUs across API versions. Diff override is similar to the existing location diffing, but it's looking for a `sku` property with `name` and `tier` sub properties, both of which match a hard-coded list of know equivalent values.

Fixes https://github.com/pulumi/pulumi-azure-native/issues/2600
Fixes https://github.com/pulumi/pulumi-azure-native/issues/2669

### Testing

1. Added a unit test to check the diff calculation.
2. Ran a manual test of upgrading a managed cluster from api `v20210501` to the default 2.0 version.

### CODE REVIEW

**Review by danielrbradley — APPROVED** [review]
Happy for this tactical fix to go in, on the condition we have an issue written up to track removing this and what it would need to be replaced with in the future.

**Comment by smcmanis** [comment]
Unfortunately this missed the case I was encountering. Which was: 
`sku`: `Base` -> `Basic`
`tier`: `Free` -> `Free` (unchanged)

**Comment by mikhailshilkov** [comment]
@smcmanis Sorry for the trouble! Let me add that test case.

**Comment by tap1992** [comment]
Is there anything else that needs to be done for this workaround to work? I've updated to v2.6.0 which seems to include this fix but I'm still seeing Pulumi trying to recreate our cluster due to the below (this is using the default API in the provider):

~ sku                      : {
              ~ name: "Basic" => "Base"

**Comment by mikhailshilkov** [comment]
@tap1992 What is the tier of your cluster?

**Comment by tap1992** [comment]
Free

**Comment by mikhailshilkov** [comment]
Opened https://github.com/pulumi/pulumi-azure-native/pull/2746 to cover the Free use case

**Pull request merged**
