### PR TITLE
Add codegen unit tests

### LINKED ISSUE #2691: Add unit tests for codegen
Rough plan:
1. Ensure we can run codegen in a unit test
2. Use snapshot testing for fast end-to-end coverage
3. Design test suite to cover key codegen features

Possible areas of testing:
- Parsing specifications
- Translation into Pulumi schema
- Calculation and application of default versions
- Parsing examples
- Generating example PCL
- Deprecation messages
- Version exclusion (normal and variants)
- Type merging for default version

### PR DESCRIPTION
**Pull request by danielrbradley**
Resolves #2691 

## Refactor

GenerateUpgradeWarnings touches the file system directly so we want to do this outside of the generation process so we can mock and test the core generation code.

- Rename gen.Constraints to gen.Versioning
- Add GetDeprecationMessage to Versioning interface
- Load NextResourcesToRemove as part of VersionSources to implement GetDeprecationMessage
- Remove old upgradePath implementation
- Aside: replace ioutil.ReadAll to fix warnings

## Example Generation

- Fix hard coded paths which blocked testing.
- Fix unreliable example generation which blocked us from re-generating the docs schema every build.

## Remove noisy generation logs

Move more output to files to unclutter the console output when running tests. These can also now be committed and tracked for significant changes in PRs. Group all output-only reports in the `reports` folder. 

New complete output of running `make schema`:

```
cd provider && go build -o /Users/dan/Dev/pulumi-azure-native/bin/pulumi-gen-azure-native -ldflags "-X github.com/pulumi/pulumi-azure-native/v2/provider/pkg/version.Version=2.0.0-alpha.0+dev" github.com/pulumi/pulumi-azure-native/v2/provider/cmd/pulumi-gen-azure-native
bin/pulumi-gen-azure-native schema 2.0.0-alpha.0+dev
Emitted "versions/v2-removed-invokes.yaml"
Emitted "versions/v2-spec.yaml"
Emitted "versions/v2-lock.json"
Emitted "reports/pathChanges.json"
Emitted "reports/allResourcesByVersion.json"
Emitted "reports/allResourceVersionsByResource.json"
Emitted "reports/active.json"
Emitted "reports/pending.json"
Emitted "reports/curationViolations.json"
Emitted "bin/schema-full.json".
Note: `provider/cmd/pulumi-resource-azure-native/schema.json` is generated by the `docs` target.
Emitted "bin/metadata-compact.json".
```

## Tests

Introduce the ability to use basic unit tests and snapshot testing for a few key scenarious:

1. Build the whole schema for a couple of specific namespace versions.
2. Snapshot test metadata which is currently completely invisible to changes due to not being committed.
3. Example generation for a specific namespace version.

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
With 13 commits and 28 file changes, it's pretty hard to review... Could you please break it down into smaller atomic PRs?

**Comment by danielrbradley** [comment]
@mikhailshilkov the commits are very atomic and should be reviewable one at a time.

**Comment by mikhailshilkov** [comment]
I will not be able to review a PR of this size efficiently.

I feel like it's the 3rd or 4th time I'm asking for smaller PRs and you don't want to break things down. What engineering work do we need to do so that small PRs wouldn't be a burden for you? Shall I bring this topic to the next ideation?

**Review by mikhailshilkov — COMMENTED** [review]
I took a look at two commits that I _think_ are related to testing. I must admit I don't understand the value prop of snapshot testing here. We added a 55k-lines file that will likely to change over time. Will we be reviewing changes to it manually? What classes of issues will it prevent? Can you link us to some examples?

Does it prevent any issues that we faced with the 2.0 release? (missing API versions, etc.)

The issue being closed mentions

> Design test suite to cover key codegen features including:
> 1. Deprecation messages
> 2. Version exclusion (normal and variants)
> 3. Type merging for default version

How are these features achieved in this PR?

Should we commit metadata.json file instead? I think `metadata-compact.json` is "just" 29 MB now.

Overall, I'd love to read more about the benefits of the approach.

**Comment by danielrbradley** [comment]
@mikhailshilkov I've split this up in to separate PRs for review:

- https://github.com/pulumi/pulumi-azure-native/pull/2705
- https://github.com/pulumi/pulumi-azure-native/pull/2706
- https://github.com/pulumi/pulumi-azure-native/pull/2707
- https://github.com/pulumi/pulumi-azure-native/pull/2708
- https://github.com/pulumi/pulumi-azure-native/pull/2709
- https://github.com/pulumi/pulumi-azure-native/pull/2710
- https://github.com/pulumi/pulumi-azure-native/pull/2711
- https://github.com/pulumi/pulumi-azure-native/pull/2712
- https://github.com/pulumi/pulumi-azure-native/pull/2713
- https://github.com/pulumi/pulumi-azure-native/pull/2714
- https://github.com/pulumi/pulumi-azure-native/pull/2715
- https://github.com/pulumi/pulumi-azure-native/pull/2716

**Pull request closed without merging**
