### PR TITLE
Upgrade pulumi/pulumi to v3.79.0 and pulumi-java to v0.9.6

### PR DESCRIPTION
**Pull request by thomas11**
I recommend reviewing commit by commit:
- Upgrade pulumi to v3.79.0 and p-java to v0.9.6
- Set Go's `internalModuleName` to `utilities` because `internal` is reserved (due to pulumi/pulumi#13749)
- Avoid null JSON arrays in active.json due to pulumi/pulumi#13311

### CODE REVIEW

**Review by mikhailshilkov — APPROVED** [review]
Changes LGTM, good to go if tests are green

**Comment by iwahbe** [comment]
@thomas11 Can you please link the java issue in this PR?

**Comment by thomas11** [comment]
> @thomas11 Can you please link the java issue in this PR?

@iwahbe I assume you're referring to the last commit, "bisect p-java issue"? That's about [the previous CI failure of this PR](https://github.com/pulumi/pulumi-azure-native/actions/runs/5996604644/job/16261582155?pr=2682).
> Could not find com.pulumi:pulumi:0.9.6

There isn't an open issue for it yet and it may be a simple error.

**Comment by thomas11** [comment]
@iwahbe Ah, that's the reason: [v0.9.6 didn't publish properly](https://github.com/pulumi/pulumi-java/actions/runs/5956804378).

**Pull request merged**
