### PR TITLE
upgrade to v3.10+ of pulumi/pulumi

### PR DESCRIPTION
**Pull request by EvanBoyle**
Draft PR to for fixes resolving https://github.com/pulumi/pulumi/issues/7595

`make build` passes locally and all SDKs compile. Once https://github.com/pulumi/pulumi/pull/7779 is merged I can update this to remove the local replaces in `pkg/go.mod`.

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
Sounds great! GitHub fails to show the changeset, I assume it's all good :)

**Comment by mikhailshilkov** [comment]
I think we do need a changelog entry for this

**Comment by EvanBoyle** [comment]
@mikhailshilkov would you mind drafting one? I looked in the changelog and bumping the codegen version from pulumi didn't seem to be included in the past.

**Comment by mikhailshilkov** [comment]
Here is an example: https://github.com/pulumi/pulumi-azure-native/pull/1006/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed

**Comment by mikhailshilkov** [comment]
I rebased and changeloged it, then went ahead and merged to avoid another conflict with the next daily build. Thank you @EvanBoyle !

**Pull request merged**
