### PR TITLE
Include invokes that didn't match our previous criteria

### PR DESCRIPTION
**Pull request by mikhailshilkov**
Resolve https://github.com/pulumi/pulumi-azure-native/issues/882 by adding a new case to when a POST endpoint becomes an Invoke:

 - Operation ID matches the pattern `Foo_GetBar`
- It's not a resource (ensured by lack of a PUT operation)
- It has to do with keys, tokens, or credentials

The list of new invokes makes a vague sense to me. Maybe, some of those things won't be needed, but some are useful.

### CODE REVIEW

**Review by lblackstone — APPROVED** [review]

**Comment by mikhailshilkov** [comment]
I have another commit that removes `listWorkspaceKeys` from the top-level module. It doesn't work anyway but it would be a compile-time breaking change to remove it. @viveklak @lblackstone do you think I should do it, or leave it alone for now (until 2.0)?

**Comment by lblackstone** [comment]
> I have another commit that removes `listWorkspaceKeys` from the top-level module. It doesn't work anyway but it would be a compile-time breaking change to remove it. @viveklak @lblackstone do you think I should do it, or leave it alone for now (until 2.0)?

If it doesn't work anyway it seems like it would be better to remove now.

**Comment by mikhailshilkov** [comment]
Looking at the .NET build failure I found out that some invokes that I added have side-effects which isn't good. I'll have to go through the list and review it more carefully. We may end up with some arbitrary rules here, unfortunately.

**Comment by mikhailshilkov** [comment]
Reduced the number of invokes to what definitely seems to make sense. The final result is the subset of the reviewed changes,  so I'll go ahead and merge.

**Pull request merged**
