### PR TITLE
Rollback codegen to pulumi/pulumi 3.6.1

### PR DESCRIPTION
**Pull request by mikhailshilkov**
Fix https://github.com/pulumi/pulumi-azure-native/issues/1092

The package size got tipped over by https://github.com/pulumi/pulumi/pull/7383 which added ~8% to the Go SDK package size, so I'm rolling back to the point before it was merged.

Let me know if you see concerns with doing so as a quick fix. We'll have to follow-up with a better fix that would allow using the latest pulumi/pulumi.

### CODE REVIEW

**Review by lblackstone — COMMENTED** [review]
This seems fairly disruptive to roll back. As an alternative, could we revert only the Go SDK changes, and temporarily disable running codegen for the Go SDK?

That would get us under the size limit without disrupting all of the other SDKs.

**Comment by mikhailshilkov** [comment]
> This seems fairly disruptive to roll back. 

While I share this concern, what are the specific disruptions here? We shipped these changes as backwards compatible... do you think they aren't compatible the other way around?

> As an alternative, could we revert only the Go SDK changes, and temporarily disable running codegen for the Go SDK?

I don't feel great about this. It would mean our Go SDK goes out of sync with the provider metadata. Resources and properties don't match anymore, so I'm not sure if we can keep pushing updates. What if a breaking change is shipped in one but not the other?

**Comment by lblackstone** [comment]
> While I share this concern, what are the specific disruptions here? We shipped these changes as backwards compatible... do you think they aren't compatible the other way around?

I don't have specific examples, but considering the large number of files this is churning in each SDK, it seems risky to me. I'm not familiar with the specific changes, so I'll defer to others' judgement on this.

> I don't feel great about this. It would mean our Go SDK goes out of sync with the provider metadata. Resources and properties don't match anymore, so I'm not sure if we can keep pushing updates. What if a breaking change is shipped in one but not the other?

That's a good point. If feature flagging like @t0yv0 suggested is not an option, then this rollback sounds like our best bet.

**Comment by mikhailshilkov** [comment]
> If inputty enum stuff was feature flagged we could turn it off on Go level while retaining ability to continue using other codegen improvements.

That would be close to ideal to me - do you see a clear path to such a change that could be done easily, quickly, and reliably? The original PR looks fairly involved to me - not sure if there's a good injection point for a feature flag. I'm happy to set the flag on the provider side, of course, that's not a problem.

**Comment by lblackstone** [comment]
> > If inputty enum stuff was feature flagged we could turn it off on Go level while retaining ability to continue using other codegen improvements.
> 
> That would be close to ideal to me - do you see a clear path to such a change that could be done easily, quickly, and reliably? The original PR looks fairly involved to me - not sure if there's a good injection point for a feature flag. I'm happy to set the flag on the provider side, of course, that's not a problem.

Hmm, indeed. I just looked at https://github.com/pulumi/pulumi/pull/7383 and it seems like feature-flagging would be rather involved and potentially risk breaking other stuff as well. Rolling back codegen specifically for azure-native seems like the least bad of these options so far.

**Comment by t0yv0** [comment]
Interesting, yes 7383 is quite involved, but I think we should still take a look at feature flagging of some sort - maybe not necessarily choice between pre-7383 and post-7383, anything that trims 7383 codegen bloat down, for example skip Map/Array helpers, or input typegen, etc..  I've put it in here for the moment https://github.com/pulumi/pulumi/issues/7835

**Pull request merged**
