### PR TITLE
Add note on app.ContainerApp API versions and KV secrets

### PR DESCRIPTION
**Pull request by thomas11**
Prompted by #3243. When creating a ContainerApp referencing a Key Vault secret via URL, Azure can at least sometimes respond with "_invalid: value or keyVaultUrl and identity should be provided_". This is a bug in the particular API version we use as default.

This PR adds a warning and a pointer later API versions to the registry docs.

### CODE REVIEW

**Review by danielrbradley — APPROVED** [review]
This looks helpful.

Out of interest, have we tried bumping the default version just to see if it's compatible?

**Comment by thomas11** [comment]
> Out of interest, have we tried bumping the default version just to see if it's compatible?

I ran this, indicating that it's not.

```
❯ schema-tools squeeze -s bin/schema-full.json --old azure-native:app:ContainerApp --new azure-native:app/v20230501:ContainerApp
Found 2 breaking changes:
Resource "azure-native:app/v20230501:ContainerApp" missing input "workloadProfileType"
Resource "azure-native:app/v20230501:ContainerApp" missing output "workloadProfileType"
```

**Comment by danielrbradley** [comment]
> > Out of interest, have we tried bumping the default version just to see if it's compatible?
> 
> I ran this, indicating that it's not.
> 
> ```
> ❯ schema-tools squeeze -s bin/schema-full.json --old azure-native:app:ContainerApp --new azure-native:app/v20230501:ContainerApp
> Found 2 breaking changes:
> Resource "azure-native:app/v20230501:ContainerApp" missing input "workloadProfileType"
> Resource "azure-native:app/v20230501:ContainerApp" missing output "workloadProfileType"
> ```

Great, thanks for confirming!

**Comment by mikhailshilkov** [comment]
If we find that the default version is broken is some meaningful way, I would support us bumping it up to a better version even with minor breaking changes. It's a trade-off, but if we can take a closer look at what happened with `workloadProfileType` and confirm it's not reducing the functionality, I think a minor break is worth to fix the defaults.

Side note: please add some description to the PR. I know it feels like busywork, but I'd really want to encourage us to keep a high bar on PR text quality.

**Comment by thomas11** [comment]
> If we find that the default version is broken in some meaningful way, I would support us bumping it up to a better version even with minor breaking changes. It's a trade-off, but if we can take a closer look at what happened with `workloadProfileType` and confirm it's not reducing the functionality, I think a minor break is worth to fix the defaults.

The difference in the spec is that `workloadProfileType` was replaced by `workloadProfileName`. Both are simple strings, but there sets of allowed values seem to be different based on the examples: `"workloadProfileType": "GeneralPurpose"` vs `"workloadProfileName": "My-GP-01"`.

So, seems like changing the API version would require everyone to update their code, not only changing the property name but also looking up the correct value. On the positive side, it's limited to that one property.

**Comment by thomas11** [comment]
Addendum: v3 of the provider is also not too far away. Overall, we've decided to leave the API version as-is.

**Pull request merged**
